# Generated by Django 5.0.7 on 2024-07-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_initial'),
        ('Enrollment', '0001_initial'),
        ('User', '0005_alter_admin_options_alter_contentcreator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollment',
        ),
    ]
