# Generated by Django 5.0.7 on 2024-07-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_admin_role_contentcreator_role_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcreator',
            name='courses',
        ),
    ]
