# Generated by Django 5.0.7 on 2024-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_initial'),
        ('User', '0003_remove_contentcreator_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcreator',
            name='courses',
            field=models.ManyToManyField(blank=True, to='Course.course'),
        ),
    ]
