# Generated by Django 5.0.7 on 2024-07-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_contentcreator_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='contentcreator',
            options={'verbose_name': 'Content Creator', 'verbose_name_plural': 'Content Creators'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='contentcreator',
            table='content_creator',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
